version: "2.0"

services:
  backend:
    build: ./backend
    depends_on:
      - db
    container_name: backend
    env_file: ./backend/docker-compose.env
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"
    restart: always

  db:
    image: library/postgres:11.8-alpine
    container_name: app_db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: top-secret
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: "no"

  redis:
    image: redis
    container_name: app_redis
    restart: always
    command: redis-server --requirepass sZA8khTCpbHkeU --loglevel debug
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

#  celery:
#    depends_on:
#      - redis
#    build: ./backend
#    container_name: blog_celery_worker
#    env_file: ./backend/docker-compose.env
#    command: celery -A config.celery worker -n default_worker -l info
#    volumes:
#      - ./backend/:/app
#    restart: "no"
#
#  celery_flower:
#    depends_on:
#      - redis
#      - celery
#      - db
#    build: ./backend
#    container_name: blog_celery_flower
#    env_file: ./backend/docker-compose.env
#    command: celery -A apps.config.celery flower --port=5555
#    ports:
#      - 5555:5555
#    restart: always
#
#  celery_beat:
#    depends_on:
#      - redis
#    build: ./backend
#    container_name: blog_celery_beat
#    env_file: ./backend/docker-compose.env
#    command: celery -A config.celery beat -l info
#    volumes:
#      - ./backend/:/app
#    restart: "no"

volumes:
  postgres_data:
  redis_data:
